Popup widow
AlaaAlsalem/Aladdin_portfolio pull request #10
Opened 2021-09-10 20:10 UTC by AlaaAlsalem

Here are the things I added to this Pull request
create a model on Html and make it hidden when the user firstly reload the page 
Add popup.js file then write the logic to handle event listener when user clicks on see project button 
Modify Styles.css file to make the design proper and customized, so it could be easily accessed

2021-09-10 20:30 UTC, rukundoeric requested changes
Hi @AlaaAlsalem, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] your `popup_window` branch has a conflict with the base branch(main), kindly perform rebase and make sure everything is okay before you request another code review. follow these simple steps to perform rebase:
    - Make sure you are on `popup_window` branch.
    - before your start, type `git status` to make sure that you don't have any uncommitted changes. if you do, commit theme.
    - then type `git rebase origin/main`. this command will put your branch in rebase mode and show you branches that have conflicts.
    - Go in each file and solve those conflicts. NOTE: You must never make a commit in this rebase mode. if you do that, you create far more worst conflict.
    - If you are done removing all conflict, the type `git add .` and then `git rebase --continue`.
    - If `git rebase --continue`  is successful, then you are done. if not, that means there are still some files or a file that still has some conflict.
    - If by any chance you make a mistake, you can always reset everything you did in rebase mode by this command    `git rebase --abort`. If you need any help, you can always reach out to me. I will be happy to help.
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-10 20:30 UTC, rukundoeric commented on index.html
>                  <h1 class="hover_hide5">Professional Art<br>Printing Data</h1>
- [ ] <b>REQUIRED:</b> The projects section should be created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). This requires changes in existing code - already created HTML code for projects list should be removed and instead it should be added via JavaScript. Check an exampe of students projects: https://github.com/olawale-o/portfolio-mobile-version/pull/15/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R95 and https://github.com/vladanvi99/my-web-portfolio/pull/15/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L96.

2021-09-10 20:30 UTC, rukundoeric commented on index.html
>          </section>
- [ ] <b>REQUIRED:</b> The projects section should be created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). This requires changes in existing code - already created HTML code for projects list should be removed and instead it should be added via JavaScript. Check an exampe of students projects: https://github.com/olawale-o/portfolio-mobile-version/pull/15/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R95 and https://github.com/vladanvi99/my-web-portfolio/pull/15/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L96.

2021-09-10 20:30 UTC, rukundoeric commented on index.html
>                                          xmlns="http://www.w3.org/2000/svg">
- [ ] <b>REQUIRED:</b> Modal popup data should be populated with the data from the projects array. that means, the medal must contain the information of the project I clicked on. But what you currently have, it will always show the same information.

2021-09-11 17:35 UTC, Davidosky007 commented
## Hi @AlaaAlsalem 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-11 17:37 UTC, merged