Mobile menu
AlaaAlsalem/Aladdin_portfolio pull request #8
Opened 2021-09-08 12:35 UTC by AlaaAlsalem

I created a new branch called mobile_menu 
modified Html file to add  div to hold the mobile menu
add javascript file called main.js to handle the event and add an event listener to the hamburger button, to display the mobile button on click

modify the styles.css file to style the mobile menu

2021-09-08 16:44 UTC, rukundoeric requested changes
Hi @AlaaAlsalem, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-08 16:44 UTC, rukundoeric commented on main.js
> +}); */
- [ ] <b>REQUIRED:</b> Kindly, try to keep your code clean by removing this commented-out codes.

2021-09-08 16:44 UTC, rukundoeric commented on main.js
> +function closePop() {
- [ ] <b>REQUIRED:<b/> Prefer using ES6 arrow function. Actually, there is nothing wrong with ES5 functions syntax but it is mandatory to use es6 features in the javascript module. besides, Arrow functions provide a simplified structure, allowing for a more concise way to write function expressions. which makes them better than ES5 functions(function declarations). Here is the syntax of an ES6 arrow function...
```javascript
  const functionName = () => {
     // code here
  }
```

2021-09-08 16:44 UTC, rukundoeric commented on styles.css
> +}
- [ ] <b>REQUIRED:</b> Kindly, try to keep your code clean by removing this commented-out codes.

2021-09-08 16:44 UTC, rukundoeric commented on styles.css
- [ ] <b>REQUIRED:</b> There is a gap on the right side when the screen is less than `1100px`.  Kindly fix it.

| <=480px      |  >480px & <1100px |
  | ----------- | ----------- |
| ![Screen Shot 2021-09-08 at 18 21 29](https://user-images.githubusercontent.com/45217364/132549733-b622bee0-e20d-4da8-b4c7-2d56de446d64.png) | ![Screen Shot 2021-09-08 at 18 40 30](https://user-images.githubusercontent.com/45217364/132550116-506b3132-3c01-41e7-a05f-db7ca01f39c4.png) |

2021-09-08 17:50 UTC, Davidosky007 commented on main.js
> +}); */
* resloved

2021-09-08 18:01 UTC, Davidosky007 commented on styles.css
* This still needs adjustment kindly fix the white on the left by making the width of the background bigger 
* [ORIGINAL]
![image](https://user-images.githubusercontent.com/52497246/132560774-5835d064-ff66-44fd-82ce-e9ca499aff0a.png)
[YOURS]
* ![image](https://user-images.githubusercontent.com/52497246/132559732-a3b26f02-03ea-498a-9332-c8d7f4d74349.png)

2021-09-08 18:04 UTC, Davidosky007 commented
## Hi @AlaaAlsalem 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
* Kindly make the requested changes requested by the previous reviewer https://github.com/AlaaAlsalem/Aladdin_portfolio/pull/8#discussion_r704596078
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-08 22:35 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @AlaaAlsalem , Good job working on some of the changes requested by the previous reviewer 👏🏼 👏🏼 

But,  there are still some which aren't addressed yet.

## Required changes :

- [ ] Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-08 22:35 UTC, safafa commented on styles.css
- [ ] Kindly make the change requested by the previous reviewer. 
![image](https://user-images.githubusercontent.com/43698511/132594224-8b5c948f-5f3d-4235-9d7b-4c7c6f4b1889.png)

- [ ] [OPTIONAL ] The menu is working. But the menu button only worked for the first time I clicked on it when I close the menu or click on the navigation link the menu Icon disappears and only appears after refreshing the page. I took the screenshot after testing the menu icon for the first time. I think fixing this issue will make a better user experience.

2021-09-09 06:48 UTC, SpaYco reviewed
Hello 👋,

_This is an additional review as a result of the second opinion request._

As the white space wasn't affected by the mobile menu and isn't part of this project, this project should be approved, however, I strongly recommend you to fix this issue and also fix the menu button disappearing after the first usage.

Keep rocking 🚀!

2021-09-11 12:17 UTC, merged